### ISSUE TITLE
ServerMapDataPacket 1.9

### ISSUE THREAD

**Issue by tetratec** [Steveice10/MCProtocolLib#150]
Does not work map (item), the first hand not visible, and in the second hand it can be moved

In the first hand: https://pp.vk.me/c604420/v604420175/147d/MmlWum2-dns.jpg
In the second hand: https://pp.vk.me/c604420/v604420175/1486/rrkbiVNMsVo.jpg

**Comment by minecraftkeba** [comment]
What has that to do with the lib? It´s a normal bug, how do you use the lib?

**Comment by tetratec** [comment]
The library is used as a server, entering the server map(item) does not work correctly on versions 1.7/1.8, everything was fine.

**Comment by minecraftkeba** [comment]
I don´t think you can use it as a server, i only use it as a client.

**Comment by tetratec** [comment]
I use as the packet generation emulate the server, but the map (item) is not displayed correctly in the hand.

**Comment by finalchild** [comment]
Can you give me the code?

**Comment by Dibro89** [comment]
@finalchild hey, I've almost the same problem but I think ServerMapDataPacket is not the cause.
Here's a simple server that allows player to join and spawn:
```
Server server = new Server(HOST, PORT, MinecraftProtocol.class, new TcpSessionFactory(PROXY));
server.setGlobalFlag(MinecraftConstants.AUTH_PROXY_KEY, AUTH_PROXY);
server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, false);
server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, (ServerLoginHandler) session
        -> {
    session.send(new ServerJoinGamePacket(0, false, GameMode.SURVIVAL, 0, Difficulty.PEACEFUL,
            10, WorldType.DEFAULT, false));
    session.send(new ServerSpawnPositionPacket(new Position(0, 90, 0)));
    session.send(new ServerPlayerPositionRotationPacket(0.0D, 90.0D, 0.0D, 90.0F, 90.0F, 0));
});
server.setGlobalFlag(MinecraftConstants.SERVER_COMPRESSION_THRESHOLD, 256);
server.bind();
```
But a normal client doesn't even send a Player Position every second.
On 1.7-1.8 same code works fine.
How can I fix this?

**Comment by finalchild** [comment]
See http://wiki.vg/Protocol_FAQ to find out how to spawn a player.

**Comment by Dibro89** [comment]
I've done this, player is spawning. But it doesnt even send PlayerPosition packets to a server.

**Comment by finalchild** [comment]
You should send map bulk packet.
See F3 information, there will be something like 'Waiting map'

**Comment by Dibro89** [comment]
Is there a way to send an empty ChunkData?

**Comment by Steveice10** [comment]
Going to close as this sounds like more of a usage problem than a bug in the library.
